fields:
    - name: url
      viewby: True
    - name: title
    - name: categories
      type: Sequence(String())
      widget:
        type: CheckboxMultiChoiceTreeCouchDB()
        options: category/all
    - name: body
      widget:
        type: TextArea()
        css_class: markitup

views:
- type: all
- type: all_count
