fields:
- name: ref
  required: True
  
- name: type

- name: num_places
  type: Integer()

- name: title

- name: categories
  type: Sequence(String())
  widget:
    type: CheckboxMultiChoiceTreeCouchDB()
    options: category/all
    

- name: leader
  type: Reference()
  refersto: leader_summary
  widget:
    type: SelectChoiceCouchDB()
    options:
      label: "%(surname)s, %(firstname)s"
      view: leader/leader_summary
    

  
views:
- type: all
- type: all_count

